#!/usr/bin/env Rscript

######  
suppressMessages(library("docopt"))
"
Usage:
	analyze_bowtie_logs.R --inpath=<inpath> --outpath=<outpath> 

Description: This script combines stats from bowtie log files. 

Options:
	--inpath=<inpath>						path to folder with bowtie files
	--outpath=<outpath> 					path to save output files
" -> doc
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load arguments:
opts <- docopt(doc)
#print(opts)
inpath <- opts$inpath
outpath <- opts$outpath

#inpath <- "/fs/cbsufsrv5/data2/japaneseEel/data/STACKS_processed/1_aligned_to_nuclear_genome_bowtie/"
#outpath <- "results/1_general_info/"


##### Parse log files:
files <- list.files(inpath, pattern = ".log")

reads_processed <- rep(0, length(files))
aligned <- rep(0, length(files))
failed_alignment <- rep(0, length(files))
discarded <- rep(0, length(files))

for (i in 1:length(files)) {
	conn <- file(paste0(inpath, files[i]), open = "r")
	lines <- readLines(conn)
	# Reads processed:
	reads_processed[i] <- as.numeric(strsplit(lines[1], split = ": ")[[1]][2])

	# Reads aligned:
	a <- strsplit(lines[2], split = ": ")[[1]][2]
	aligned[i] <- as.numeric(strsplit(a, split = " \\(")[[1]][1])

	# Reads failed to align:
	b <- strsplit(lines[3], split = ": ")[[1]][2]
	failed_alignment[i] <- as.numeric(strsplit(b, split = " \\(")[[1]][1])

	# Reads discarded:
	c <- strsplit(lines[4], split = ": ")[[1]][2]
	discarded[i] <- as.numeric(strsplit(c, split = " \\(")[[1]][1])
	close(conn)
}

##### Add up over all samples and save to file:
# Sum over all samples:
total_reads_processed <- sum(reads_processed)
total_aligned <- sum(aligned)
total_failed_alignment <- sum(failed_alignment)
total_discarded <- sum(discarded)

# Save to file:
sink(paste0(outpath, "bowtie_log_info_all_samples.txt"))
print(paste0("Total reads processed: ", total_reads_processed))
print(paste0("Total reads aligned: ", total_aligned))
print(paste0("Total reads failing alignment: ", total_failed_alignment))
print(paste0("Total reads discarded: ", total_discarded))
sink()



print("DONE!")