#!/usr/bin/env Rscript

######  
suppressMessages(library("docopt"))
"
Usage:
	ANOVA_script.R --sumstats_file=<sumstats_file> --outpath=<outpath>
	
Description: This script will run ANOVAs for the eel paper. 

Options:
	--sumstats_file=<sumstats_file>			sumstats file
	--outpath=<outpath> 					path to save output files
" -> doc
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################


##### Load arguments:
opts <- docopt(doc)
#print(opts)
sumstats_file <- opts$sumstats_file
outpath <- opts$outpath

#sumstats_file <- "data/STACKS_processed/4_depth_optimization/m3/rxstacks_corrected/coverage_filtered/batch_1.sumstats.tsv"
#outpath <- "results/7_ANOVA/"



##### Load libraries:
library("dplyr")



##### Read in data
sumstats <- read.table(sumstats_file, sep = "\t", header = FALSE, stringsAsFactors = FALSE)
colnames(sumstats) <- c("Batch_ID", "Locus_ID", "Chr", "BP", "Col", "Pop_ID", "P_Nuc", "Q_Nuc", "N", "P", "Obs_Het", "Obs_Hom", "Exp_Het", "Exp_Hom", "Pi", "Smoothed_Pi", "Smoothed_Pi_P-value", "Fis", "Smoothed_Fis", "Smoothed_Fis_P-value", "Private")
popcodes <- read.table("data/sample_info/popcodes.txt", sep = "\t", header = FALSE, stringsAsFactors = FALSE)



##### Rename PopID variabes and exclude outgroup:
sumstats$Pop_ID <- popcodes$V2[match(sumstats$Pop_ID, popcodes$V1)]
sumstats <- sumstats %>%
	filter(Pop_ID != "Hainan14")
	


##### Calculate ANOVA followed by Tukey for He, Ho, Fis, Pi, and Private:	
He <- TukeyHSD(aov(sumstats$Exp_Het ~ sumstats$Pop_ID))
Ho <- TukeyHSD(aov(sumstats$Obs_Het ~ sumstats$Pop_ID))
Fis <- TukeyHSD(aov(sumstats$Fis ~ sumstats$Pop_ID))
Pi <- TukeyHSD(aov(sumstats$Pi ~ sumstats$Pop_ID))
Private <- TukeyHSD(aov(sumstats$Private ~ sumstats$Pop_ID))



##### Combine into one table and white out P > 0.01:
Ps <- cbind(He$`sumstats$Pop_ID`[,4], Ho$`sumstats$Pop_ID`[,4], Fis$`sumstats$Pop_ID`[,4], Pi$`sumstats$Pop_ID`[,4], Private$`sumstats$Pop_ID`[,4])
colnames(Ps) <- c("He", "Ho", "Fis", "Pi", "Private")

Ps_whiteout <- Ps
Ps_whiteout[which(Ps_whiteout < 0.01, arr.ind = TRUE)] <- ""


##### Save both tables:
write.table(Ps, paste0(outpath, "table_Tukey_ANOVA_p_values_11_japanese_eel_pops.txt"), sep = "\t", quote = FALSE)
write.table(Ps_whiteout, paste0(outpath, "table_Tukey_ANOA_p_values_11_japanese_eel_pops_whiteout_P_less_than_0.01.txt"), quote = FALSE)



