#!/usr/bin/env Rscript

######  
suppressMessages(library("docopt"))
"
Usage:
	create_stacks_running_scripts.R --pop_map=<pop_map> --b=<b> --p=<p> --io_path=<io_path> --outfile=<outfile> 

Description: This script will generate a shell script that will run stacks using the parameters specified on command line. 

Options:
	--pop_map=<pop_map> 			population map file for stacks
	--b=<b>							MySQL batchID
	--p=<p>							number of threads to use
	--io_path=<io_path>				path for input/output
	--outfile=<outfile>				name of qqplot file to save

" -> doc
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load arguments:
opts <- docopt(doc)
#print(opts)
pop_map <- opts$pop_map
b <- opts$b
p <- opts$p
io_path <- opts$io_path
outfile <- opts$outfile

#pop_map <- "../data/sample_info/population_file_for_stacks.txt"
#b <- "2"
#p <- "4"
#io_path <- "../data/STACKS_processed/6_ref_map_output_files_nuclear_corrected/"
#outfile <- "stack_run_script_test.sh"



##### Read in population file:
pmap <- read.table(file=pop_map, sep="\t", header=FALSE, stringsAsFactor=FALSE)



##### Start script:
script <- "#!/bin/bash"
script <- c(script, "")



##### Rebuild the catalog (cstacks):
# -b = MySQL ID of this batch [b]
# -p = number of threads to use
# -o = output path to write results
# -g = base catalog matching on genomic location, not sequence identity. 
# -s = each sample path

# Create one long strig with all of the samples listed after -s:
dash_s <- c()
for (i in 1:dim(pmap)[1]) {
	dash_s <- c(dash_s, paste0("-s ", io_path, pmap$V1[i], " "))
}
dash_s <- paste(dash_s, collapse = '')

# Add to script:
script <- c(script, "echo 'Running cstacks to build catalog'")
script <- c(script, paste0("/programs/stacks-1.48/bin/cstacks -b ", b, " -p ", p, " -o ", io_path, " -g ", dash_s, "2>&1"))
script <- c(script, "")



##### Rematch against the catalog (sstacks):
# -b = MySQL ID of this batch [b]
# -p = number of threads to use
# -o = output path to write results
# -g = base matching on genomic location, not sequence identity
# -c = catalog file (from previous step)
# -s = each sample path

# Add to script:
script <- c(script, "echo 'Running sstacks to rematch to catalog'")
script <- c(script, paste0("/programs/stacks-1.48/bin/sstacks -b ", b, " -p ", p, " -o ", io_path, " -g -c ",io_path, "batch_", b, " ", dash_s, "2>&1"))



##### Write out script:
write.table(script, outfile, sep="\n", quote=FALSE, col.names=FALSE, row.names=FALSE)

print("DONE!")
