#!/usr/bin/env Rscript

###### 
# This script will generate the barcode file for Stacks. 
# ./make_map_for_eelseq_project.R 
# input: 	txt file with coordinates
# output: 	map with samples
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################


##### load libraries:
suppressMessages(library(dplyr))
library("ggplot2")
suppressMessages(library("ggmap"))
library("ggsn")
#library("maps")
#library("mapproj")
#library("mapdata")
#suppressMessages(library("rgeos"))
#suppressMessages(library("maptools"))
#library("sp")
#suppressMessages(library("raster"))
#suppressMessages(library("rgdal"))
#suppressMessages(library("dismo"))

source("scripts/common_functions_for_eelseq_analyses.R")



##### Load data:
samples <- read.table("data/sample_info/eelseq_sample_info_degrees_removed_corrected_with_names_coordinates_fixed.txt", sep="\t", header=TRUE, stringsAsFactors=FALSE)
samples$latitude <- as.numeric(gsub("N", "", samples$latitude))



##### Pull out the location data:
reps <- samples[seq(1,60,5),]
pops <- reps %>% 
	filter(population %in% c("LCG09", "XH", "FQ", "CX", "DF", "Q", "H", "HM"))

# Reorder levels for plot
pops$pop_name <- factor(pops$pop_name, levels = c("Chiba-ken", "Kagawa", "Jiangsu province", "Yangtze River estuary", "Zhejiang province", "Fujian province", "Guangdong province", "Hainan province"))



##### Set up the base of the map:
range(samples$latitude)
range(samples$longitude)

# Function for population colors:
pop.shapes <- function(x) {
	if (x == "Chiba-ken") {
		return(0)
	} else if (x == "Kagawa") {
		return(1)
	} else if (x == "Jiangsu province") {
		return(19)
	} else if (x == "Yangtze River estuary") {
#		return("deepskyblue4")
		return(18) 
	} else if (x == "Zhejiang province") {
		return(17)
	} else if (x == "Fujian province") {
		return(20)
	} else if (x == "Guangdong province") {
		return(15)
	} else if (x == "Hainan province") {
		return(13)
	}
}

# Get shapes:
myShapes <- sapply(pops$pop_name, pop.shapes)
names(myShapes) <- pops$pop_name

# Get colors:
myColors <- sapply(pops$pop_name, pop.cols)
names(myColors) <- pops$pop_name




##### Plot the map

##### USE THIS BASE FOR GOOGLEMAPS
#base = get_map(location=c(103, 20, 150, 36), maptype="roadmap", color="bw", source="google", messaging=FALSE, zoom = 4)

#base = get_map(location=c(103, 20, 150, 36), maptype="toner-lite", source = "stamen", color="bw", messaging=FALSE)

#base.map=ggmap(base)
#map.plot <- base.map + 
#	geom_point(data=pops, aes(x=longitude, y= latitude, shape = pop_name), color = "white", size = 5) +
#	geom_point(data=pops, aes(x=longitude, y= latitude, shape = pop_name), color="black", size=4) +
#	scale_shape_manual(values = sapply(levels(pops$pop_name), pop.cols), labels = levels(pops$pop_name), name = "population") +
#	labs(x="Longitude", y="Latitude", title="Collection sites") +
#	theme_bw() + 
#	theme(	axis.text = element_text(size = 12), 
#			axis.title = element_text(size = 16),
#			plot.title = element_text(size = 20, face = "bold"),
#			legend.key = element_rect(color = "white")) +
	# USE THIS SCALE BAR FOR GOOGLE MAP:
	#scalebar(data=pops, location="bottomright", dist=500, height=0.05, dd2km=TRUE, st.dist=0.1, st.size=2, model="WGS84", y.min=10, y.max=55, x.min=100, x.max=150)

#ggsave(filename="results/1_general_info/map_sample_locations.pdf", plot = map.plot, device = "pdf", width = 6, height = 5)


##### USE THIS BASE FOR STAMENMAPS (black and white color)
base = get_map(location=c(103, 15, 150, 38), color="bw", maptype="toner-lite", source="stamen", messaging=FALSE, zoom = 4)

base.map=ggmap(base)
map.plot <- base.map + 
	geom_point(data=pops, aes(x=longitude, y= latitude, shape = pop_name), color = "white", size = 5) +
	geom_point(data=pops, aes(x=longitude, y= latitude, shape = pop_name), color="black", size=4) +
	scale_shape_manual(values = sapply(levels(pops$pop_name), pop.shapes), labels = levels(pops$pop_name), name = "population") +
	labs(x="Longitude", y="Latitude", title="Collection sites") +
	theme_bw() + 
	theme(	axis.text = element_text(size = 12), 
			axis.title = element_text(size = 16),
			plot.title = element_text(size = 20, face = "bold"),
			legend.key = element_rect(color = "white")) +
	# USE THIS SCALE BAR FOR STAMEN MAP:
	scalebar(data=pops, location="bottomright", dist=500, height=0.05, dd2km=TRUE, st.dist=0.1, st.size=2, model="WGS84", y.min=15, y.max=38, x.min=100, x.max=150)

ggsave(filename="results/1_general_info/map_sample_locations_bw.pdf", plot = map.plot, device = "pdf", width = 6, height = 4)


# Plot timeline
y <- c(1,1,1,1,1,2,3,4,5,1,2,1)

pdf("results/1_general_info/timeline_sample_collection_bw.pdf", width=8, height=2.8)
par(mar=c(5,2,3,2))
plot(reps$year, y, pch=sapply(reps$pop_name, pop.shapes), col="black", cex=2, ylim=c(0,6), main="Collection year", xlab="Year", yaxt="n", bty="n", xlim=c(2000, 2014), ylab="", cex.main=2, cex.axis=1.5, cex.lab=2)
trash <- dev.off()



##### USE THIS BASE FOR STAMENMAPS (with color)
#base.map=ggmap(base)
#map.plot <- base.map + 
#	geom_point(data=pops, aes(x=longitude, y= latitude), color="white", shape=myShapes, size=5) +
#	geom_point(data=pops, aes(x=longitude, y=latitude, color=pop_name), shape = myShapes, size=4) + 
#	scale_shape_manual(values = sapply(levels(pops$pop_name), pop.shapes), labels = levels(pops$pop_name), name = "population") +
#	scale_color_manual(values = sapply(levels(pops$pop_name), pop.cols), labels = levels(pops$pop_name), name = "population") +
#	labs(x="Longitude", y="Latitude", title="Collection sites") +
#	theme_bw() + 
#	theme(	axis.text = element_text(size = 12), 
#			axis.title = element_text(size = 16),
#			plot.title = element_text(size = 20, face = "bold"),
#			legend.key = element_rect(color = "white")) +
#	# USE THIS SCALE BAR FOR STAMEN MAP:
#	scalebar(data=pops, location="bottomright", dist=500, height=0.05, dd2km=TRUE, st.dist=0.1, st.size=2, model="WGS84", y.min=15, y.max=38, x.min=100, x.max=150)



base.map=ggmap(base)
map.plot <- base.map + 
	geom_point(data=pops, aes(x=longitude, y= latitude), color="white", shape = 16, size=5) +
	geom_point(data=pops, aes(x=longitude, y=latitude, color=pop_name), shape = 16, size=4) + 
	scale_color_manual(values = sapply(levels(pops$pop_name), pop.cols), labels = levels(pops$pop_name), name = "population") +
	labs(x="Longitude", y="Latitude", title="Collection sites") +
	theme_bw() + 
	theme(	axis.text = element_text(size = 12), 
			axis.title = element_text(size = 16),
			plot.title = element_text(size = 20, face = "bold"),
			legend.key = element_rect(color = "white")) +
	# USE THIS SCALE BAR FOR STAMEN MAP:
	scalebar(data=pops, location="bottomright", dist=500, height=0.05, dd2km=TRUE, st.dist=0.1, st.size=2, model="WGS84", y.min=15, y.max=38, x.min=100, x.max=150)

ggsave(filename="results/1_general_info/map_sample_locations.pdf", plot = map.plot, device = "pdf", width = 6, height = 4)


# Plot timeline
y <- c(1,1,1,1,1,2,3,4,5,1,2,1)

pdf("results/1_general_info/timeline_sample_collection.pdf", width=8, height=2.8)
par(mar=c(5,2,3,2))
plot(reps$year, y, pch=16, col=sapply(reps$pop_name, pop.cols), cex=2, ylim=c(0,6), main="Collection year", xlab="Year", yaxt="n", bty="n", xlim=c(2000, 2014), ylab="", cex.main=2, cex.axis=1.5, cex.lab=2)
trash <- dev.off()

print("DONE!")
