#!/usr/bin/env Rscript

###### 
# This script will generate a population map file for STACKS. 
# ./make_population_map_file_for_STACKS.R 
# input: 	txt file barcode information
#			txt file of sample information
# output: 	population map file for stacks
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################


##### load libraries:
suppressMessages(library(dplyr))
library("testit")



##### Load data:
barcodes <- read.table("data/sample_info/eel_p2_barcode_info.txt", sep="\t", header=TRUE, stringsAsFactors=FALSE)
sample_info <- read.table("data/sample_info/eelseq_sample_info_degrees_removed.txt", sep="\t", header=TRUE, stringsAsFactors=FALSE)



##### Double check sample and barcode names match:
testing <- match(sample_info$sample_ID, barcodes$sample_name_2)
issues <- which(is.na(testing))

# 5 of those issues are that the barcodes are HM#, while the sample sheet lists HM-#
sample_info$sample_ID <- gsub("HM-", "HM", sample_info$sample_ID)

# There is an additional space before "DFDC-13" that needs to be removed:
sample_info$sample_ID <- gsub(" DFDC-13", "DFDC-13", sample_info$sample_ID)

# Retest to make sure all the sample names match:
testing <- match(sample_info$sample_ID, barcodes$sample_name_2)
issues <- which(is.na(testing))
assert(length(issues) == 0)



##### Generate population file:
popfile <- sample_info %>%
	select(sample_ID, population)



##### Save population file and corrected sample info:
write.table(sample_info, "data/sample_info/eelseq_sample_info_degrees_removed_corrected.txt", sep="\t", row.names=FALSE, quote=FALSE)
write.table(popfile, "data/sample_info/population_file_for_stacks.txt", sep="\t", row.names=FALSE, col.names=FALSE, quote=FALSE)



print("DONE!")