#!/usr/bin/env Rscript

###### 
# This script will generate the barcode file for Stacks. 
# ./make_bcfiles_for_STACKS.R 
# input: 	txt file barcode information
# output: 	bcfile for each of the three fastq files of EELseq data
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################


##### load libraries:
suppressMessages(library(dplyr))



##### Load data:
barcodes <- read.table("data/sample_info/eel_p2_barcode_info.txt", sep="\t", header=TRUE, stringsAsFactors=FALSE)



##### create barcode files:
manli1 <- barcodes %>%
	filter(library.name=="manli1") %>%
	select(index, sample_name_2)

manli2 <- barcodes %>%
	filter(library.name=="manli2") %>%
	select(index, sample_name_2)
	
# Can't have dashes in file, so change dashes to underscores:
# manli1$sample_name_2 <-  gsub("-", "_", manli1$sample_name_2)
# manli2$sample_name_2 <-  gsub("-", "_", manli2$sample_name_2)
	


##### Save barcode files:
write.table(manli1, "data/sample_info/bcfile_manli1_for_stacks.txt", sep="\t", quote=FALSE, row.names=FALSE, col.names=FALSE)
write.table(manli2, "data/sample_info/bcfile_manli2_for_stacks.txt", sep="\t", quote=FALSE, row.names=FALSE, col.names=FALSE)


print("DONE!")