#!/usr/bin/env Rscript

######  
suppressMessages(library("docopt"))
"
Usage:
	plot_admixture_CVs.R --cv_file=<cv_file> --outfile=<outfile>

Description: This script will plot the standard error from the admixture cross-validations (to choose the correct K)

Options:
	--file=<file>				plink map file
	--outfile=<outfile>			name of what to save for plink outfile
" -> doc
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load arguments:
opts <- docopt(doc)
cv_file <- opts$cv_file
outfile <- opts$outfile

#cv_file <- "../results/8_admixture/m10/all_individuals/admixture_cross_validations.txt"
#outfile <- "../results/8_admixture/m10/all_individuals/plot_admixture_cross_validations.pdf"


##### Load libraries:
library(ggplot2)
suppressMessages(library(dplyr))



##### Read in data:
cv <- read.table(cv_file, sep=" ", header=FALSE)



##### Parse data and plot:
cv$V3 <- gsub("\\(K=", "", gsub("):", "", cv$V3))
colnames(cv) <- c("CV", "error", "K", "CVE")
cv <- arrange(cv, as.numeric(K))
cv$K <- as.numeric(as.character(cv$K))


plot1 <- ggplot(cv, aes(x = K, y = CVE, group = 1)) +
	geom_point(colour = "gray30", size = 2) +
	geom_line(colour = "gray30") +
	scale_x_continuous(name = "K (number of populations)", breaks = seq(1, max(cv$K), 1), labels = seq(1, max(cv$K), 1), limits = range(cv$K)) +
	theme_classic() +
	labs(title = "Admixture cross-validation error rates by K", y = "cross-validation error")

ggsave(outfile, plot1, width=5, height=3.5)

print("DONE!")


