#!/usr/bin/env Rscript

######  
suppressMessages(library("docopt"))
"
Usage:
	plot_loci_per_population.R --m3=<m3> --m6=<m6> --m10=<m10> --pop_info=<pop_info> --outpath=<outpath> 

Description: Will generate Figure 2

Options:
	--m3=<m3>								sumstats_summary_tail.tsv
	--m6=<m6>								sumstats_summary_tail.tsv
	--m10=<m10>								sumstats_summary_tail.tsv
	--pop_info=<pop_info>					table of population information
	--outpath=<outpath> 					path to save output files
" -> doc
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load libraries:
suppressMessages(library("ggplot2"))



##### Load arguments:
opts <- docopt(doc)
#print(opts)
m3 <- opts$m3
m6 <- opts$m6
m10 <- opts$m10
pop_info <- opts$pop_info
outpath <- opts$outpath

#m3 <- "results/3_optimizing_depth/batch_1.sumstats_summary_tail.tsv"
#m6 <- "results/3_optimizing_depth/batch_3.sumstats_summary_tail.tsv"
#m10 <- "results/3_optimizing_depth/batch_4.sumstats_summary_tail.tsv"
#pop_info <- "data/sample_info/eelseq_sample_info_degrees_removed_corrected_with_names_coordinates_fixed.txt"
#outpath <- "results/3_optimizing_depth/"



##### Read in data:
m3_data <- read.table(m3, sep = "\t", stringsAsFactors = FALSE, comment.char ="", header = TRUE)
m6_data <- read.table(m6, sep = "\t", stringsAsFactors = FALSE, comment.char ="", header = TRUE)
m10_data <- read.table(m10, sep = "\t", stringsAsFactors = FALSE, comment.char ="", header = TRUE)
pops <- read.table(pop_info, sep = "\t", stringsAsFactors = FALSE, header = TRUE)



##### Reformat data to plot:
# Add depth variable to each table:
m3_data$depth = 3
m6_data$depth = 6
m10_data$depth = 10

# Combine into one table:
var_data <- rbind(m3_data, m6_data, m10_data)

# Make pop/year combo:
pops$popyear <- paste0(pops$pop_name, " - ", pops$year)

# Make population and popyear lookup table:
popyeartab <- pops[, which(colnames(pops) %in% c("population", "popyear"))]
pyt <- subset(popyeartab, !duplicated(popyeartab))

# Add to var_data table:
var_data$popyear <- pyt$popyear[match(var_data$X..Pop.ID, pyt$population)]



##### Plot number of variant loci per population, stack depth 

plot1 <- ggplot(data = var_data, aes(x = popyear, y = Variant.Sites, fill = as.factor(depth))) +
	geom_bar(stat = "identity", position = position_dodge()) +
	theme_bw() +
	theme(axis.text.x = element_text(angle = 45, size = 11, hjust = 0.95)) +
	xlab("") +
	ylab("# Variant Sites") +
	scale_fill_manual("Minimum\nstack\ndepth", values = c("3" = "grey70", "6" = "grey50", "10" = "grey30"))
	
ggsave(paste0(outpath, "barplot_variant_sites_per_pop_across_min_stack_depths.pdf"), plot = plot1, width = 8, height = 6)



print("DONE!")