#!/usr/bin/env Rscript

######  
suppressMessages(library("docopt"))
"
Usage:
	plot_PCA.R --full_plink_in=<full_plink_in> --part_plink_in=<part_plink_in> --outpath=<outpath>

Description: This script will generate a PCA plot of the eel samples

Options:
	--full_plink_in=<full_plink_in>				prefix on plink eigenval and eigenvec files
	--part_plink_in=<part_plink_in>		prefix on plink eigenval and eigenvec files (outgroup excluded from calculations)
	--outpath=<outpath>				path of where to save output
" -> doc
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load arguments:
opts <- docopt(doc)
full_plink_in <- opts$full_plink_in
part_plink_in <- opts$part_plink_in
outpath <- opts$outpath

# full_plink_in <- "../data/STACKS_processed/7_depth_optimization/m3/rxstacks_corrected/coverage_filtered/batch_2.plink.for.admixture.pca"
# part_plink_in <- "../data/STACKS_processed/7_depth_optimization/m3/rxstacks_corrected/coverage_filtered/batch_2.plink.for.admixture.pca.no.hainan"
# outpath <- "../results/9_PCA/m3/"



##### Load common functions:
source("scripts/common_functions_for_eelseq_analyses.R")



##### Read in data:
print("reading in data")
evals <- read.table(paste0(full_plink_in, ".eigenval"), sep="\n")
evecs <- read.table(paste0(full_plink_in, ".eigenvec"), sep=" ", header=FALSE)
evalsNoOut <- read.table(paste0(part_plink_in, ".eigenval"), sep="\n")
evecsNoOut <- read.table(paste0(part_plink_in, ".eigenvec"), sep=" ", header=FALSE)



##### Generate output folder if it isn't there already:
if (!file.exists(outpath)) {
	print(paste0("creating ",outpath," in filesystem"))
	dir.create(file.path(outpath))
}



##### Plot PCA (all samples):
# Calculate percent variance explained by each PC:
PVE <- round(evals$V1/sum(evals$V1), 2)

# Stuff for legend:
forLegend <- unique(pops$pop_name)

print("saving PCA plot")

# Black and White:
# pdf(paste(outpath, "PCA.all.samples.",today,"ERD.pdf", sep=""), width=6, height=6)
# plot(evecs[,3], evecs[,4], pch=sapply(evecs$V1, pop.pch), cex=1.5, xlab=paste("PC 1 -", (PVE[1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(PVE[2]*100),"% of variance",sep=" ")) 
# legend("bottomleft", cex=0.75, pch=sapply(forLegend, pop.pch), legend=forLegend, bty="n")
# hi <- dev.off()

# Color:
pdf(paste(outpath, "PCA.all.samples.",today,"ERD.pdf", sep=""), width=6, height=6)
plot(evecs[,3], evecs[,4], pch=16, col = sapply(evecs$V1, pop.cols), cex=1.5, xlab=paste("PC 1 -", (PVE[1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(PVE[2]*100),"% of variance",sep=" ")) 
legend("bottomleft", cex=0.75, pch=16, fill = sapply(forLegend, pop.cols), legend=forLegend, bty="n")
hi <- dev.off()



##### Plot PCA (outgroup excluded):
# Calculate percent variance explained by each PC:
PVENoOut <- round(evalsNoOut$V1/sum(evalsNoOut$V1), 2)

# Stuff for legend:
forLegend <- forLegend[-which(forLegend == "Hainan province")]

print("saving PCA plot")

# Black and White:
# pdf(paste(outpath, "PCA.no.outgroup.",today,"ERD.pdf", sep=""), width=6, height=6)
# plot(evecsNoOut[,3], evecsNoOut[,4], pch=sapply(evecsNoOut$V1, pop.pch), col=rgb(0,0,0, alpha = 0.5), cex=1.5, xlab=paste("PC 1 -", (PVENoOut[1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(PVENoOut[2]*100),"% of variance",sep=" ")) 
# legend("topleft", cex=0.75, pch=sapply(forLegend, pop.pch), legend=forLegend, bty="n")
# hi <- dev.off()

# Color:
pdf(paste(outpath, "PCA.no.outgroup.",today,"ERD.pdf", sep=""), width=6, height=6)
plot(evecsNoOut[,3], evecsNoOut[,4], pch=16, col = sapply(evecsNoOut$V1, pop.cols), cex=1.5, xlab=paste("PC 1 -", (PVENoOut[1]*100),"% of variance", sep=" "),ylab=paste("PC 2 -",(PVENoOut[2]*100),"% of variance",sep=" ")) 
legend("topleft", cex=0.75, pch=16, fill = sapply(forLegend, pop.cols), legend=forLegend, bty="n")
hi <- dev.off()

  
print("DONE!")