#!/usr/bin/env Rscript

######  
suppressMessages(library("docopt"))
"
Usage:
	plot_admixture_barchart.R --Q_file=<Q_file> --fam_file=<fam_file> --K=<K> --outfile=<outfile>

Description: This script will plot the standard error from the admixture cross-validations (to choose the correct K)

Options:
	--Q_file=<Q_file>			Q file from admixture
	--fam_file=<fam_file>		plink fam file put through admixture
	--K=<K>						number of K from admixture
	--outfile=<outfile>			name of what to save for plink outfile
" -> doc
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load arguments:
opts <- docopt(doc)
Q_file <- opts$Q_file
fam_file <- opts$fam_file
sample_file <- opts$sample_info
K <- opts$K
outfile <- opts$outfile

#Q_file <- "../results/8_admixture/m10/all_individuals/batch_4.plink.for.admixture.missingness.cleaned.10.Q"
#fam_file <- "../data/STACKS_processed/7_depth_optimization/m10/rxstacks_corrected/coverage_filtered/batch_4.plink.for.admixture.missingness.cleaned.fam"
#K <- 10
#outfile <- "../results/8_admixture/m10/all_individuals/plot_admixture_K10.pdf"



##### Read in data:
Q <- read.table(Q_file, sep=" ", header=FALSE)
fam <- read.table(fam_file, sep=" ", header=FALSE)
samples <- read.table("data/sample_info/eelseq_sample_info_degrees_removed_corrected_with_names_coordinates_fixed.txt", sep="\t", header=TRUE, stringsAsFactors=FALSE)



##### Reformat sample data:
samples$latitude <- as.numeric(gsub("N", "", samples$latitude))
pops <- unique(samples[,-which(colnames(samples) %in% c("sample_ID"))])
pops$lat_help <- c(4, 4, 4, 4, 4, 7, 6, 5, 3, 1, 2, 8)
pops$popName <- paste0(pops$pop_name, " - ", pops$lat_help, " - ", pops$year)



##### Plot admixture plot:
mypops <- pops$popName[match(fam$V1, pops$population)]
mycols <- c("cornflowerblue", "firebrick", "gold", "mediumorchid3", "lightslategray", 
			"lightpink3", "darkorange3", "lightcyan3", "olivedrab3", "snow2")

pdf(outfile, width=8, height=5)
par(mar=c(9,4,4,2))
barplot(t(as.matrix(Q)), col=mycols, ylab="Ancestry", main=paste0("Admixture analysis, K = ", K), border=NA, las=2, names.arg=mypops, cex.names=0.5)
t <- dev.off()


print("DONE!")