#!/usr/bin/env Rscript

######  
suppressMessages(library("docopt"))
"
Usage:
	plot_variants_per_sample.R --vcf_stats_counts_file=<vcf_stats_counts_file> --desc=<desc> --outpath=<outpath>

Description: This script will plot the number of SNPs identified per sample. 

Options:
	--vcf_stats_counts_file=<vcf_stats_counts_file>		vcf.stats.counts file
	--desc=<desc>										description of data plotted
	--outpath=<outpath>									path to save plot
" -> doc
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load arguments:
opts <- docopt(doc)
vcf_stats_counts_file <- opts$vcf_stats_counts_file
desc <- opts$desc
outpath <- opts$outpath

#vcf_stats_counts_file <- "../data/STACKS_processed/7_depth_optimization/m3/rxstacks_corrected/batch_2.vcf.stats.counts"
#desc <- "m3"
#outpath <- "../results/5_optimizing_depth/"



##### Load libraries and source common functions:
suppressMessages(library(dplyr))
source("scripts/common_functions_for_eelseq_analyses.R")



##### Read in data:
vcf <- read.table(file=vcf_stats_counts_file, sep="\t", header=FALSE)



##### Process data:
vcf <- vcf[-which(vcf$V2 == "all"),]
vcf$V2 <- gsub("samples/", "", vcf$V2)
vcf$population <- samples$population[match(vcf$V2, samples$sample_ID)]
vcf$popName <- samples$popName[match(vcf$V2, samples$sample_ID)]
vcf <- arrange(vcf, population)



##### Plot barchart
pdf(paste0(outpath, desc,"_barplot_SNPs_per_sample_in_vcf_before_coverage_filtering_",today,"ERD.pdf"), width=8, height=5)
par(mar=c(9,4,4,2))
barplot(vcf$V1, col=sapply(vcf$population, pop.cols), main=paste0("SNPs per sample - ", desc), ylab="# SNPs", cex.names=0.5, names.arg=vcf$popName, las=2)
muffins <- dev.off()

print("DONE!")